<a href="https://colab.research.google.com/github/gy23/PracticeMachineLearning/blob/master/Practice_Label_Encoding_and_One_Hot_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Label Encoding

In [8]:
from sklearn.preprocessing import LabelEncoder

items = ['IT', 'Finance', 'Manufacturing', 'Real Estate', 'Service']

# Generate an object and 'fit and transform'
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print(labels)

[1 0 2 3 4]


In [9]:
print('Encoding class:', encoder.classes_)

Encoding class: ['Finance' 'IT' 'Manufacturing' 'Real Estate' 'Service']


In [12]:
print('Decoding:', encoder.inverse_transform([1, 0, 2, 3, 4]))

Decoding: ['IT' 'Finance' 'Manufacturing' 'Real Estate' 'Service']


### Cannot use LabelEncoding for Regressor, but can use for Classifier

# One-Hot Encoding

In [15]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# ***Change labels as 2D matrix***
labels = labels.reshape(-1,1)

# First, Label Encoding => labels
# Second, Change labels as 2D matrix
# Third, Use the result from LabelEncoding

oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

print(oh_labels.toarray())

[[0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# Get_Dummies in Pandas DataFrame for One-hot Encoding

In [16]:
import pandas as pd

df = pd.DataFrame({'item': ['IT', 'Finance', 'Manufacturing', 'Real Estate', 'Service']})
pd.get_dummies(df)

item_Finance  item_IT  item_Manufacturing  item_Real Estate  item_Service
0             0        1                   0                 0             0
1             1        0                   0                 0             0
2             0        0                   1                 0             0
3             0        0                   0                 1             0
4             0        0                   0                 0             1