# Understanding PolynomialFeatures

In [1]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

In [5]:
X = np.arange(4).reshape(2,2)
X

array([[0, 1],
       [2, 3]])

In [6]:
poly = PolynomialFeatures(degree=2)
poly.fit(X)
poly_ftr = poly.transform(X)
poly_ftr

array([[1., 0., 1., 0., 0., 1.],
       [1., 2., 3., 4., 6., 9.]])

In [7]:
def polynomial_func(X):
    y = 1 + 2 * X + X ** 2 + X ** 3
    return y

In [9]:
y = polynomial_func(X)
y

array([[ 1,  5],
       [17, 43]])

In [10]:
poly_ftr = PolynomialFeatures(degree=3).fit_transform(X)
poly_ftr

array([[ 1.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.,  8., 12., 18., 27.]])

In [12]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(poly_ftr, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [13]:
print('Polynomial Regression Coefficient\n', np.round(model.coef_, 2))
print('Polynomial Regression Shape: ', model.coef_.shape)

Polynomial Regression Coefficient
 [[0.   0.02 0.02 0.05 0.07 0.1  0.1  0.14 0.22 0.31]
 [0.   0.06 0.06 0.11 0.17 0.23 0.23 0.34 0.51 0.74]]
Polynomial Regression Shape:  (2, 10)


# Using Pipeline

In [14]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
import numpy as np

def polynomial_func(X):
    y = 1 + 2 * X + X ** 2 + X ** 3
    return y

X = np.arange(4).reshape(2,2)
y = polynomial_func(X)

model = Pipeline([('poly', PolynomialFeatures(degree=3)), ('linear', LinearRegression())])
model = model.fit(X, y)
print('Polynomial Regression Coefficient\n', np.round(model.named_steps['linear'].coef_, 2))

Polynomial Regression Coefficient
 [[0.   0.02 0.02 0.05 0.07 0.1  0.1  0.14 0.22 0.31]
 [0.   0.06 0.06 0.11 0.17 0.23 0.23 0.34 0.51 0.74]]
